syntax = "proto3";

package er;

import "BattleSkillEnum.proto";
import "AbilityEnum.proto";

option java_package = "er.proto";
option java_multiple_files = true;

message BattleSkillList {
  repeated BattleSkill skill = 1;
  repeated BattleSkillTemplate template = 2;
}

message BattleSkill {
  BattleSkillEnum id = 1;
  string name = 2;
  string announce_string = 3;
}

message BattleSkillTemplate {
  BattleSkillTemplateEnum id = 1;
  string name = 2;

  message BattleSkillTemplateParam {
    oneof param {
      AbilityEnum ability = 1;
    }
  }

  message BattleSkillTemplateParamStrings {
    string announce_string = 1;
    repeated BattleSkillTemplateParam param = 2;
  }
  repeated BattleSkillTemplateParamStrings valid_params = 3;

  message BattleSkillTemplateImpl {
    BattleSkillEnum id = 1;
    repeated BattleSkillTemplateParam param = 2;
  }
  repeated BattleSkillTemplateImpl impl = 4;
}
