# proto-file: BattleSkillList.proto
# proto-message: er.BattleSkillList

template {
  id: SKILL_TEMPLATE_EXTRA_ABILITY
  name: "Extra Ability"
  valid_params {
    announce_string: "{B_TRAINER1_NAME}'s team gains the\\nability {B_BUFF1}!"
    param {
      ability: ABILITY_NONE
    }
  }
  valid_params {
    announce_string: "{B_TRAINER1_NAME}'s team gains the\\nabilities {B_BUFF1} and {B_BUFF2}!"
    param {
      ability: ABILITY_NONE
    }
    param {
      ability: ABILITY_NONE
    }
  }
  valid_params {
    announce_string: "{B_TRAINER1_NAME}'s team gains the\\nabilities {B_BUFF1}, {B_BUFF2},\\pand {B_BUFF3}!"
    param {
      ability: ABILITY_NONE
    }
    param {
      ability: ABILITY_NONE
    }
    param {
      ability: ABILITY_NONE
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_UNNERVE
    param {
      ability: ABILITY_UNNERVE
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_INNARDS_OUT
    param {
      ability: ABILITY_INNARDS_OUT
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_CUTE_CHARM
    param {
      ability: ABILITY_CUTE_CHARM
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_FILTER
    param {
      ability: ABILITY_FILTER
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_SWORD_OF_RUIN
    param {
      ability: ABILITY_SWORD_OF_RUIN
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_FLASH_FIRE
    param {
      ability: ABILITY_FLASH_FIRE
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_SWARM
    param {
      ability: ABILITY_SWARM
    }
  }
  impl {
    id: SKILL_EXTRA_ABILITY_SUPER_LUCK
    param {
      ability: ABILITY_SUPER_LUCK
    }
  }
}

skill {
  id: SKILL_NONE
  name: "---"
}
skill {
  id: SKILL_EVIOLITE
  name: "Eviolite"
  announce_string: "{B_TRAINER1_NAME}'s team is protected by\\nEviolite."
}
skill {
  id: SKILL_PERMANENT_STICKY_WEB
  name: "Sticky Web"
  announce_string: "A sticky web spreads out on the\\nground around {B_PLAYER_NAME}'s team!"
}
skill {
  id: SKILL_SPIKES_1_LAYER
  name: "Spikes 1x"
  announce_string: "A layer of spikes scatters on the\\nground around {B_PLAYER_NAME}'s team!"
}
skill {
  id: SKILL_ON_ENTRY_LEECH_SEED
  name: "Leech Seed"
  announce_string: "A seed was planted on {B_DEF_NAME_WITH_PREFIX}!"
}
skill {
  id: SKILL_TOXIC_SPIKES_2_LAYERS
  name: "Toxic Spikes 2x"
  announce_string: "Two layers of Toxic Spikes scatter on the\\nground around {B_PLAYER_NAME} team!"
}
skill {
  id: SKILL_HAZARDS_ALL
  name: "All Hazards"
  # TODO: Come up with better announce string for this skill
  announce_string: "All hazards were scattered around {B_PLAYER_NAME}'s team!"
}
skill {
  id: SKILL_ON_END_TURN_MOVE_JUDGEMENT_60_BP
  name: "Judgement on Turn End"
  announce_string: "{B_TRAINER1_NAME}'s team uses 60 BP Judgement on turn end!"
}
skill {
  id: SKILL_ON_SWITCH_MOVE_PAYDAY
  name: "Payday on Switch"
  announce_string: "{B_TRAINER1_NAME}'s team uses Payday whenever\\na Pokémon switches!"
}
skill {
  id: SKILL_NO_CRIT
  name: "Critical Hit Immunity"
  announce_string: "{B_TRAINER1_NAME}'s team is immune to critical hits!"
}
skill {
  id: SKILL_STEALTH_ROCKS
  name: "Stealth Rock"
  announce_string: "Pointed stones float in the air\\naround {B_PLAYER_NAME}'s team!"
}
skill {
  id: SKILL_PERMANENT_INVERSE_ROOM
  name: "Inverse Room"
  # TODO: Come up with a better announce string
  announce_string: "An unknown power inverts type effectiveness!"
}
skill {
  id: SKILL_PERMANENT_RAINBOW
  name: "Rainbow"
  announce_string: "A rainbow appears in the sky over \\n{B_TRAINER1_NAME}'s team!"
}
skill {
  id: SKILL_PERMANENT_SWAMP
  name: "Swamp"
  announce_string: "A swamp envelops {B_PLAYER_NAME}'s team!"
}
skill {
  id: SKILL_PERMANENT_FIRE_SEA
  name: "Sea of Fire"
  announce_string: "A sea of fire surrounds {B_PLAYER_NAME}'s team!"
}