# proto-file: MoveBehaviorConfigList.proto
# proto-message: er.MoveBehaviorConfigList

behavior {
  id: EFFECT_HIT
  attack { }
}
behavior {
  id: EFFECT_SLEEP
  status {
    do {
      status: STATUS_SLEEP
    }
  }
}
behavior {
  id: EFFECT_POISON_HIT
  attack {
    effect { effect: MOVE_EFFECT_POISON }
  }
}
behavior {
  id: EFFECT_ABSORB
  attack {
    absorb_damage: true
  }
  healing_effect: true
}
behavior {
  id: EFFECT_BURN_HIT
  attack {
    effect { effect: MOVE_EFFECT_BURN }
  }
}
behavior {
  id: EFFECT_PARALYZE_HIT
  attack {
    effect { effect: MOVE_EFFECT_PARALYSIS }
  }
}
behavior {
  id: EFFECT_EXPLOSION
  attack {
    attack_all_in_loop {
      before_loop {
        target: TARGET_MOVE_USER
        change_percent_hp: -100
        hp_drain_lethal: true
      }
    }
  }
}
behavior {
  id: EFFECT_SELF_DESTRUCT
  attack {
    attack_all_in_loop {
      before_loop {
        target: TARGET_MOVE_USER
        change_percent_hp: -100
        hp_drain_lethal: true
      }
    }
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_MOVE_USER
        damaged_by: TARGET_ALL
      }
    }
  }
}
behavior {
  id: EFFECT_DREAM_EATER
  attack {
    require {
      status: STATUS_SLEEP
    }
    absorb_damage: true
  }
}
behavior {
  id: EFFECT_MIRROR_MOVE
  custom_behavior: true
}
behavior {
  id: EFFECT_ATTACK_UP
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_UP
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SPEED_UP
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_ATTACK_UP
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_DEFENSE_UP
  status {
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_ACCURACY_UP
  status {
    do {
      change_stat {
        stat: STAT_ACC
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_EVASION_UP
  status {
    do {
      change_stat {
        stat: STAT_EVASION
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_ATTACK_UP_3
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 3
      }
    }
  }
}
behavior {
  id: EFFECT_ATTACK_DOWN
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_DOWN
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_SPEED_DOWN
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_ATTACK_DOWN
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_DEFENSE_DOWN
  status {
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_ACCURACY_DOWN
  status {
    do {
      change_stat {
        stat: STAT_ACC
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_EVASION_DOWN
  status {
    do {
      change_stat {
        stat: STAT_EVASION
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_HAZE
  status {
    do {
      other: OTHER_CLEAR_STAT_CHANGES
    }
  }
}
behavior {
  id: EFFECT_BIDE
  custom_behavior: true
}
behavior {
  id: EFFECT_RAMPAGE
  attack {
    min_lock_turns: 2
    max_lock_turns: 3
    after_locked_turns_end {
      target: TARGET_MOVE_USER
      status: STATUS_CONFUSE
    }
  }
}
behavior {
  id: EFFECT_ROAR
  status {
    do {
      switch {
        random: true
      }
    }
  }
}
behavior {
  id: EFFECT_MULTI_HIT
  attack {
    multihit {
      type: MULTIHIT_FIVE
      require {
        target: TARGET_MOVE_USER
        ability: ABILITY_SKILL_LINK
      }
    }
    multihit {
      type: MULTIHIT_FOUR_OR_FIVE
      require {
        target: TARGET_MOVE_USER
        item: ITEM_LOADED_DICE
      }
    }
    multihit { type: MULTIHIT_TWO_TO_FIVE }
    effect_from_argument: true
  }
}
behavior {
  id: EFFECT_WATER_SHURIKEN
  attack {
    multihit {
      type: MULTIHIT_FIVE
      require {
        target: TARGET_MOVE_USER
        ability: ABILITY_SKILL_LINK
      }
    }
    multihit {
      type: MULTIHIT_THREE
      require {
        target: TARGET_MOVE_USER
        species: SPECIES_GRENINJA_ASH
      }
    }
    multihit {
      type: MULTIHIT_FOUR_OR_FIVE
      require {
        target: TARGET_MOVE_USER
        item: ITEM_LOADED_DICE
      }
    }
    multihit { type: MULTIHIT_TWO_TO_FIVE }
    effect_from_argument: true
    power_modifier {
      flat: 20
      require {
        target: TARGET_MOVE_USER
        species: SPECIES_GRENINJA_ASH
      }
    }
  }
}
behavior {
  id: EFFECT_CONVERSION
  status {
    do {
      other: OTHER_CHANGE_TYPE_TO_FIRST_MOVE
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_FLINCH_HIT
  attack {
    effect { effect: MOVE_EFFECT_FLINCH }
  }
}
behavior {
  id: EFFECT_RESTORE_HP
  status {
    do {
      change_percent_hp: 50
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_TOXIC
  status {
    do {
      status: STATUS_TOXIC
    }
  }
}
behavior {
  id: EFFECT_PAY_DAY
  attack {
    effect { effect: MOVE_EFFECT_PAYDAY }
    power_modifier {
      flat: 120
      require {
        target: TARGET_MOVE_USER
        species: SPECIES_MEOWTH_PARTNER
        species: SPECIES_MEOWTH_PARTNER_MEGA
      }
      require {
        target: TARGET_MOVE_USER
        item: ITEM_AMULET_COIN
      }
    }
    change_target {
      new_type: BOTH
      require {
        target: TARGET_MOVE_USER
        item: ITEM_AMULET_COIN
      }
    }
  }
}
behavior {
  id: EFFECT_LIGHT_SCREEN
  status {
    do {
      status: STATUS_LIGHT_SCREEN
    }
  }
}
behavior {
  id: EFFECT_TRI_ATTACK
  attack {
    random_effect {
      effect { effect: MOVE_EFFECT_PARALYSIS }
      effect { effect: MOVE_EFFECT_FROSTBITE }
      effect { effect: MOVE_EFFECT_BURN }
    }
  }
}
behavior {
  id: EFFECT_REST
  custom_behavior: true
  healing_effect: true
}
behavior {
  id: EFFECT_FUSION_COMBO
  attack {
    power_modifier {
      multiplier: 2
      require {
        fusion_combo: true
      }
    }
  }
}
behavior {
  id: EFFECT_SUPER_FANG
  attack {
    percent_hp_damage: 50
  }
}
behavior {
  id: EFFECT_DRAGON_RAGE
  attack {
    flag_damage: 40
  }
}
behavior {
  id: EFFECT_TRAP
  attack {
    effect { effect: MOVE_EFFECT_WRAP }
  }
}
behavior {
  id: EFFECT_HEAL_BLOCK
  status {
    do {
      status: STATUS_HEAL_BLOCK
    }
  }
}
behavior {
  id: EFFECT_DOUBLE_HIT
  attack {
    multihit { type: MULTIHIT_TWO }
  }
}
behavior {
  id: EFFECT_DRAGON_DARTS
  attack {
    multihit { type: MULTIHIT_TWO }
    power_modifier {
      multiplier: 1.25
      require {
        target: TARGET_MOVE_USER
        ability: ABILITY_PARENTAL_BOND
      }
    }
    switch_targets_each_hit: true
  }
}
behavior {
  id: EFFECT_RECOIL_IF_MISS
  attack {
    on_miss {
      target: TARGET_MOVE_USER
      change_percent_hp: -25
      hp_drain_lethal: true
    }
  }
}
behavior {
  id: EFFECT_MIST
  status {
    do {
      status: STATUS_MIST
    }
  }
}
behavior {
  id: EFFECT_FOCUS_ENERGY
  status {
    do {
      change_stat {
        stat: STAT_CRIT
        amount: 2
      }
      alt_success_string: "{B_DEF_ATK_NAME_WITH_PREFIX} is getting pumped!"
    }
  }
}
behavior {
  id: EFFECT_RECOIL_25
  attack {
    recoil_fraction: 4
  }
}
behavior {
  id: EFFECT_CONFUSE
  status {
    do {
      status: STATUS_CONFUSE
    }
  }
}
behavior {
  id: EFFECT_ATTACK_UP_2
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_UP_2
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_SPEED_UP_2
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_ATTACK_UP_2
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_DEFENSE_UP_2
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_ACCURACY_UP_2
  status {
    do {
      change_stat {
        stat: STAT_ACC
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_EVASION_UP_2
  status {
    do {
      change_stat {
        stat: STAT_EVASION
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_TRANSFORM
  custom_behavior: true
}
behavior {
  id: EFFECT_ATTACK_DOWN_2
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_DOWN_2
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_SPEED_DOWN_2
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_ATTACK_DOWN_2
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_DEFENSE_DOWN_2
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_ACCURACY_DOWN_2
  status {
    do {
      change_stat {
        stat: STAT_ACC
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_EVASION_DOWN_2
  status {
    do {
      change_stat {
        stat: STAT_EVASION
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_REFLECT
  status {
    do {
      status: STATUS_REFLECT
    }
  }
}
behavior {
  id: EFFECT_POISON
  status {
    do {
      status: STATUS_POISON
    }
  }
}
behavior {
  id: EFFECT_PARALYZE
  status {
    do {
      status: STATUS_PARALYZE
    }
  }
}
behavior {
  id: EFFECT_ATTACK_DOWN_HIT
  attack {
    effect { effect: MOVE_EFFECT_ATK_MINUS_1 }
  }
}
behavior {
  id: EFFECT_DEFENSE_DOWN_HIT
  attack {
    effect { effect: MOVE_EFFECT_DEF_MINUS_1 }
  }
}
behavior {
  id: EFFECT_SPEED_DOWN_HIT
  attack {
    effect { effect: MOVE_EFFECT_SPD_MINUS_1 }
  }
}
behavior {
  id: EFFECT_SPECIAL_ATTACK_DOWN_HIT
  attack {
    effect { effect: MOVE_EFFECT_SP_DEF_MINUS_1 }
  }
}
behavior {
  id: EFFECT_SPECIAL_DEFENSE_DOWN_HIT
  attack {
    effect { effect: MOVE_EFFECT_SP_ATK_MINUS_1 }
  }
}
behavior {
  id: EFFECT_ACCURACY_DOWN_HIT
  attack {
    effect { effect: MOVE_EFFECT_ACC_MINUS_1 }
  }
}
behavior {
  id: EFFECT_EVASION_DOWN_HIT
  attack {
    effect { effect: MOVE_EFFECT_EVS_MINUS_1 }
  }
}
behavior {
  id: EFFECT_TWO_TURNS_ATTACK
  two_turn {
    turn_2_attack { }
  }
}
behavior {
  id: EFFECT_CONFUSE_HIT
  attack {
    effect { effect: MOVE_EFFECT_CONFUSION }
  }
}
behavior {
  id: EFFECT_SUBSTITUTE
  status {
    do {
      change_percent_hp: -25
      failure_fails_move: true
    }
    do {
      status: STATUS_SUBSTITUTE
      failure_fails_move: true
    }
  }
}
behavior {
  id: EFFECT_RECHARGE
  attack {
    effect {
      effect: MOVE_EFFECT_RECHARGE
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_METRONOME
  custom_behavior: true
}
behavior {
  id: EFFECT_LEECH_SEED
  status {
    do {
      status: STATUS_LEECH_SEED
    }
  }
}
behavior {
  id: EFFECT_DISABLE
  status {
    do {
      status: STATUS_DISABLE
    }
  }
}
behavior {
  id: EFFECT_LEVEL_DAMAGE
  attack {
    level_damage: true
  }
}
behavior {
  id: EFFECT_COUNTER
  attack {
    counter_damage {
      multiplier: 2
      type: COUNTERS_PHYSICAL
    }
  }
}
behavior {
  id: EFFECT_ENCORE
  status {
    do {
      status: STATUS_ENCORE
    }
  }
}
behavior {
  id: EFFECT_PAIN_SPLIT
  custom_behavior: true
}
behavior {
  id: EFFECT_SNORE
  attack {
    require {
      target: TARGET_MOVE_USER
      status: STATUS_SLEEP
    }
    effect { effect: MOVE_EFFECT_FLINCH }
  }
}
behavior {
  id: EFFECT_CONVERSION_2
  status {
    do {
      other: OTHER_CHANGE_TYPE_TO_FIRST_MOVE
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_LOCK_ON
  status {
    do {
      status: STATUS_ALWAYS_HIT
    }
  }
}
behavior {
  id: EFFECT_SKETCH
  custom_behavior: true
}
behavior {
  id: EFFECT_HAMMER_ARM
  attack {
    effect {
      effect: MOVE_EFFECT_SPD_MINUS_1
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_SLEEP_TALK
  custom_behavior: true
}
behavior {
  id: EFFECT_DESTINY_BOND
  status {
    do {
      status: STATUS_DESTINY_BOND
    }
  }
}
behavior {
  id: EFFECT_FLAIL
  attack {
    crit_modifier {
      amount: 3
      require {
        not: true
        hp_percent: 25
      }
    }
  }
}
behavior {
  id: EFFECT_SPITE
  status {
    do {
      reduce_pp {
        min: 4
        max: 4
      }
    }
  }
}
behavior {
  id: EFFECT_FALSE_SWIPE
  attack {
    effect_from_argument: true
    no_ko: true
  }
}
behavior {
  id: EFFECT_HEAL_BELL
  status {
    do {
      other: OTHER_CLEAR_STATUS
    }
    do {
      target: TARGET_PARTNER
      other: OTHER_CLEAR_STATUS
    }
    do {
      other: OTHER_CLEAR_PARTY_STATUS
    }
    do {
      change_percent_hp: 30
    }
  }
}
behavior {
  id: EFFECT_TRIPLE_KICK
  attack {
    power_modifier {
      hit_count: true
    }
    multihits_can_miss: true
  }
}
behavior {
  id: EFFECT_THIEF
  attack {
    effect { effect: MOVE_EFFECT_STEAL_ITEM }
    priority {
      amount: 1
      require {
        target: TARGET_MOVE_USER
        item: ITEM_NONE
        require {
          not: true
          item: ITEM_NONE
        }
      }
    }
  }
}
behavior {
  id: EFFECT_MEAN_LOOK
  status {
    do {
      status: STATUS_PREVENT_ESCAPE
    }
  }
}
behavior {
  id: EFFECT_NIGHTMARE
  attack {
    require {
      status: STATUS_SLEEP
    }
    effect { effect: MOVE_EFFECT_NIGHTMARE }
  }
}
behavior {
  id: EFFECT_MINIMIZE
  status {
    do {
      status: STATUS_MINIMIZED
    }
    do {
      change_stat {
        stat: STAT_EVASION
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_CURSE
  custom_behavior: true
}
behavior {
  id: EFFECT_HEALING_WISH
  custom_behavior: true
  healing_effect: true
}
behavior {
  id: EFFECT_PROTECT
  status {
    protect_effect: true
    do {
      other: OTHER_SET_PROTECT
    }
  }
}
behavior {
  id: EFFECT_SPIKES
  status {
    do {
      status: STATUS_SPIKES
    }
  }
}
behavior {
  id: EFFECT_FORESIGHT
  status {
    do {
      status: STATUS_FORESIGHT
    }
  }
}
behavior {
  id: EFFECT_PERISH_SONG
  status {
    do {
      target: TARGET_ALL
      status: STATUS_PERISH_SONG
    }
  }
}
behavior {
  id: EFFECT_SANDSTORM
  status {
    do {
      set_weather: WEATHER_SANDSTORM
    }
    change_target {
      new_type: ALL_BATTLERS
      require {
        target: TARGET_MOVE_USER
        not: true
        ability: ABILITY_FORECAST
      }
    }
  }
}
behavior {
  id: EFFECT_ENDURE
  status {
    do {
      status: STATUS_ENDURE
    }
  }
}
behavior {
  id: EFFECT_ROLLOUT
  attack {
    increment_rollout_counter: true
    power_modifier {
      rollout_counter: true
    }
  }
}
behavior {
  id: EFFECT_SWAGGER
  status {
    do {
      status: STATUS_CONFUSE
    }
    do {
      change_stat {
        stat: STAT_ATK
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_ATTRACT
  status {
    do {
      status: STATUS_ATTRACT
    }
  }
}
behavior {
  id: EFFECT_SAFEGUARD
  status {
    do {
      status: STATUS_SAFEGUARD
    }
  }
}
behavior {
  id: EFFECT_MAGNITUDE
  custom_behavior: true
}
behavior {
  id: EFFECT_BATON_PASS
  status {
    do {
      switch {
        copy_volatile: true
      }
    }
  }
}
behavior {
  id: EFFECT_PURSUIT
  custom_behavior: true
}
behavior {
  id: EFFECT_RAPID_SPIN
  attack {
    effect {
      effect: MOVE_EFFECT_RAPIDSPIN
      affects_user: true
      certain: true
    }
    additional_effect {
      effect: MOVE_EFFECT_SPD_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_CAPTIVATE
  attack {
    power_modifier {
      multiplier: 2
      require {
        status: STATUS_ATTRACT
      }
    }
  }
}
behavior {
  id: EFFECT_MORNING_SUN
  status {
    do {
      other: OTHER_RESTORE_HP_WEATHER_BASED
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_SYNTHESIS
  status {
    do {
      other: OTHER_RESTORE_HP_WEATHER_BASED
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_MOONLIGHT
  status {
    do {
      other: OTHER_RESTORE_HP_WEATHER_BASED
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_HIDDEN_POWER
  attack {
    type_change {
      hidden_power: true
    }
  }
}
behavior {
  id: EFFECT_RAIN_DANCE
  status {
    do {
      set_weather: WEATHER_RAIN
    }
    change_target {
      new_type: ALL_BATTLERS
      require {
        target: TARGET_MOVE_USER
        not: true
        ability: ABILITY_FORECAST
      }
    }
  }
}
behavior {
  id: EFFECT_SUNNY_DAY
  status {
    do {
      set_weather: WEATHER_SUN
    }
    change_target {
      new_type: ALL_BATTLERS
      require {
        target: TARGET_MOVE_USER
        not: true
        ability: ABILITY_FORECAST
      }
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_UP_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_DEF_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_ATTACK_UP_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_ATK_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_ALL_STATS_UP_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_ALL_STATS_UP
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_FELL_STINGER
  attack {
    on_faint_target {
      change_stat {
        stat: STAT_ATK
        amount: 3
      }
    }
  }
}
behavior {
  id: EFFECT_BELLY_DRUM
  status {
    do {
      change_percent_hp: -50
      failure_fails_move: true
    }
    do {
      change_stat {
        stat: STAT_ATK
        amount: 12
      }
      failure_fails_move: true
      alt_success_string: "{B_ATK_NAME_WITH_PREFIX} cut its own HP and maximized Attack!"
    }
  }
}
behavior {
  id: EFFECT_PSYCH_UP
  status {
    do {
      other: OTHER_COPY_STATS
    }
  }
}
behavior {
  id: EFFECT_MIRROR_COAT
  attack {
    counter_damage {
      multiplier: 2
      type: COUNTERS_SPECIAL
    }
  }
}
behavior {
  id: EFFECT_FUTURE_SIGHT
  custom_behavior: true
}
behavior {
  id: EFFECT_SOLARBEAM
  two_turn {
    accelerate_if {
      target: TARGET_MOVE_USER
      weather_affected: WEATHER_SUN
      ability: ABILITY_CHLOROPLAST
    }
    turn_2_attack {
      power_modifier {
        multiplier: .5
        require {
          target: TARGET_MOVE_USER
          weather_affected: WEATHER_RAIN
          require {
            not: true
            target: TARGET_MOVE_USER
            ability: ABILITY_CHLOROPLAST
          }
        }
      }
    }
  }
}
behavior {
  id: EFFECT_THUNDER
  attack {
    effect { effect: MOVE_EFFECT_PARALYSIS }
    accuracy {
      always_hit: true
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_RAIN
      }
    }
    accuracy {
      set_to: 50
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_SUN
      }
    }
  }
}
behavior {
  id: EFFECT_SWITCH
  status {
    do {
      switch { }
    }
  }
}
behavior {
  id: EFFECT_SAFE_PASSAGE
  status {
    do {
      switch {
        after {
          status: STATUS_SAFE_PASSAGE
        }
      }
    }
  }
}
behavior {
  id: EFFECT_BEAT_UP
  custom_behavior: true
}
behavior {
  id: EFFECT_SEMI_INVULNERABLE
  two_turn {
    turn_1 {
      do {
        status: STATUS_SEMI_INVULNERABLE
      }
    }
    turn_2_attack {
      before {
        remove_status: STATUS_SEMI_INVULNERABLE
      }
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_CURL
  status {
    do {
      status: STATUS_CURL_UP
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SOFTBOILED
  status {
    do {
      change_percent_hp: 50
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_FAKE_OUT
  attack {
    effect { effect: MOVE_EFFECT_FLINCH }
    require {
      is_first_turn: true
    }
  }
}
behavior {
  id: EFFECT_STOCKPILE
  status {
    do {
      status: STATUS_STOCKPILE
      failure_fails_move: true
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SPIT_UP
  attack {
    type_change {
      first_type: true
    }
  }
  use_stockpile_before_pp: true
}
behavior {
  id: EFFECT_SWALLOW
  status {
    do {
      change_percent_hp: 50
    }
  }
  use_stockpile_before_pp: true
}
behavior {
  id: EFFECT_WORRY_SEED
  status {
    do {
      status: STATUS_FEAR
    }
    do {
      set_ability: ABILITY_INSOMNIA
    }
  }
}
behavior {
  id: EFFECT_HAIL
  status {
    do {
      set_weather: WEATHER_HAIL
    }
    change_target {
      new_type: ALL_BATTLERS
      require {
        target: TARGET_MOVE_USER
        not: true
        ability: ABILITY_FORECAST
      }
    }
  }
}
behavior {
  id: EFFECT_TORMENT
  status {
    do {
      status: STATUS_TORMENT
    }
  }
}
behavior {
  id: EFFECT_FLATTER
  status {
    do {
      status: STATUS_CONFUSE
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_WILL_O_WISP
  status {
    do {
      status: STATUS_BURN
    }
  }
}
behavior {
  id: EFFECT_MEMENTO
  status {
    before_animation {
      change_percent_hp: -100
      hp_drain_lethal: true
    }
    do {
      change_stat {
        stat: STAT_ATK
        amount: -2
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_FACADE
  attack {
    power_modifier {
      multiplier: 1.5
      require {
        target: TARGET_MOVE_USER
        status: STATUS_STATUS1_ANY
      }
    }
    ignore_status_stat_drops: true
  }
}
behavior {
  id: EFFECT_FOCUS_PUNCH
  attack {
    round_start_announce: "{B_ATK_NAME_WITH_PREFIX} is tightening its focus!"
    before {
      print: "{B_ATK_NAME_WITH_PREFIX} lost its focus!"
      require {
        target: TARGET_MOVE_USER
        damaged_by: TARGET_ALL
      }
    }
    power_modifier {
      flat: 40
      require {
        target: TARGET_MOVE_USER
        damaged_by: TARGET_ALL
      }
    }
  }
}
behavior {
  id: EFFECT_SMELLINGSALT
  attack {
    after {
      target: TARGET_MOVE_USER
      other: OTHER_CLEAR_STATUS
    }
  }
}
behavior {
  id: EFFECT_FOLLOW_ME
  status {
    do {
      status: STATUS_FORCE_TARGET
    }
  }
}
behavior {
  id: EFFECT_CHARGE
  status {
    do {
      status: STATUS_CHARGE
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_TAUNT
  status {
    do {
      status: STATUS_TAUNT
    }
  }
}
behavior {
  id: EFFECT_HELPING_HAND
  status {
    do {
      status: STATUS_HELPING_HAND
    }
  }
}
behavior {
  id: EFFECT_TRICK
  status {
    do {
      other: OTHER_SWAP_ITEMS
    }
  }
}
behavior {
  id: EFFECT_ROLE_PLAY
  status {
    do {
      copy_ability_to: TARGET_MOVE_USER
    }
  }
}
behavior {
  id: EFFECT_WISH
  status {
    do {
      other: OTHER_WISH
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_ASSIST
  custom_behavior: true
}
behavior {
  id: EFFECT_INGRAIN
  status {
    do {
      status: STATUS_INGRAIN
    }
  }
}
behavior {
  id: EFFECT_SUPERPOWER
  attack {
    effect {
      effect: MOVE_EFFECT_ATK_DEF_DOWN
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_MAGIC_COAT
  status {
    do {
      status: STATUS_MAGIC_COAT
    }
  }
}
behavior {
  id: EFFECT_RECYCLE
  status {
    do {
      other: OTHER_RESTORE_ITEM
    }
  }
}
behavior {
  id: EFFECT_REVENGE
  attack {
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_MOVE_USER
        damaged_by: TARGET_MOVE_TARGET
      }
    }
  }
}
behavior {
  id: EFFECT_BRICK_BREAK
  attack {
    before {
      other: OTHER_CLEAR_SCREENS
    }
  }
}
behavior {
  id: EFFECT_YAWN
  status {
    do {
      status: STATUS_DROWSY
    }
  }
}
behavior {
  id: EFFECT_KNOCK_OFF
  attack {
    effect { effect: MOVE_EFFECT_KNOCK_OFF }
    power_modifier {
      multiplier: 1.5
      require {
        can_lose_item: true
      }
    }
  }
}
behavior {
  id: EFFECT_ENDEAVOR
  attack {
    reduce_to_user_hp: true
  }
}
behavior {
  id: EFFECT_ERUPTION
  attack {
    power_modifier {
      percent_hp: TARGET_MOVE_USER
    }
  }
}
behavior {
  id: EFFECT_SKILL_SWAP
  status {
    do {
      other: OTHER_SWAP_ABILITIES
    }
  }
}
behavior {
  id: EFFECT_IMPRISON
  status {
    do {
      status: STATUS_IMPRISON
    }
  }
}
behavior {
  id: EFFECT_REFRESH
  status {
    do {
      other: OTHER_CLEAR_STATUS
    }
    do {
      change_percent_hp: 25
    }
  }
}
behavior {
  id: EFFECT_GRUDGE
  status {
    do {
      status: STATUS_GRUDGE
    }
  }
}
behavior {
  id: EFFECT_SNATCH
  status {
    do {
      status: STATUS_SNATCH
    }
  }
}
behavior {
  id: EFFECT_LOW_KICK
  attack {
    power_modifier {
      flat: 120
      require {
        weight: 2000
      }
    }
    power_modifier {
      flat: 100
      require {
        weight: 1000
      }
    }
    power_modifier {
      flat: 80
      require {
        weight: 500
      }
    }
    power_modifier {
      flat: 60
      require {
        weight: 250
      }
    }
    power_modifier {
      flat: 40
      require {
        weight: 100
      }
    }
    power_modifier {
      flat: 20
    }
  }
}
behavior {
  id: EFFECT_RECOIL_33
  attack {
    recoil_fraction: 3
  }
}
behavior {
  id: EFFECT_TEETER_DANCE
  status {
    do {
      target: TARGET_ALL
      status: STATUS_CONFUSE
    }
  }
}
behavior {
  id: EFFECT_HIT_ESCAPE
  attack {
    after {
      switch { }
    }
  }
}
behavior {
  id: EFFECT_MUD_SPORT
  status {
    do {
      status: STATUS_MUD_SPORT
    }
  }
}
behavior {
  id: EFFECT_POISON_FANG
  attack {
    effect { effect: MOVE_EFFECT_TOXIC }
  }
}
behavior {
  id: EFFECT_WEATHER_BALL
  attack {
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_ANY
      }
    }
    type_change {
      weather: true
    }
  }
}
behavior {
  id: EFFECT_OVERHEAT
  attack {
    effect {
      effect: MOVE_EFFECT_SP_ATK_MINUS_2
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_TICKLE
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: -1
      }
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_COSMIC_POWER
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: -1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_BULK_UP
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_WATER_SPORT
  status {
    do {
      status: STATUS_MUD_SPORT
    }
  }
}
behavior {
  id: EFFECT_CALM_MIND
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_DRAGON_DANCE
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_CAMOUFLAGE
  status {
    do {
      other: OTHER_CHANGE_TYPE_TO_TERRAIN
    }
  }
}
behavior {
  id: EFFECT_FLING
  attack {
    require {
      target: TARGET_MOVE_USER
      can_lose_item: true
    }
    type_change {
      item_type: true
      require {
        target: TARGET_MOVE_USER
        hold_effect: HOLD_EFFECT_GEMS
      }
    }
    power_modifier {
      flat: 130
      require {
        target: TARGET_MOVE_USER
        item: ITEM_BIG_NUGGET
        item: ITEM_IRON_BALL
      }
    }
    additional_effect {
      effect: MOVE_EFFECT_FLINCH
      require {
        target: TARGET_MOVE_USER
        hold_effect: HOLD_EFFECT_FLINCH
      }
    }
    additional_effect {
      effect: MOVE_EFFECT_BURN
      require {
        target: TARGET_MOVE_USER
        item: ITEM_FLAME_ORB
      }
    }
    additional_effect {
      effect: MOVE_EFFECT_TOXIC
      require {
        target: TARGET_MOVE_USER
        item: ITEM_TOXIC_ORB
      }
    }
    additional_effect {
      effect: MOVE_EFFECT_FROSTBITE
      require {
        target: TARGET_MOVE_USER
        item: ITEM_FROST_ORB
      }
    }
    additional_effect {
      effect: MOVE_EFFECT_PARALYSIS
      require {
        target: TARGET_MOVE_USER
        item: ITEM_LIGHT_BALL
      }
    }
    additional_effect {
      effect: MOVE_EFFECT_POISON
      require {
        target: TARGET_MOVE_USER
        item: ITEM_BLACK_SLUDGE
        item: ITEM_POISON_BARB
      }
    }
    after {
      target: TARGET_MOVE_USER
      other: OTHER_LOSE_ITEM
    }
  }
}
behavior {
  id: EFFECT_NATURAL_GIFT
  attack {
    require {
      target: TARGET_MOVE_USER
      item_pocket: POCKET_BERRIES
    }
    type_change {
      natural_gift: true
    }
    power_modifier {
      natural_gift: true
    }
    effect_from_natural_gift: true
  }
}
behavior {
  id: EFFECT_WAKE_UP_SLAP
  attack {
    power_modifier {
      multiplier: 2
      require {
        status: STATUS_SLEEP
      }
    }
    after {
      other: OTHER_CLEAR_STATUS
      require {
        status: STATUS_SLEEP
      }
    }
  }
}
behavior {
  id: EFFECT_HEX
  attack {
    effect_from_argument: true
    power_modifier {
      multiplier: 2
      require {
        status: STATUS_STATUS1_ANY
      }
    }
  }
}
behavior {
  id: EFFECT_ASSURANCE
  attack {
    power_modifier {
      multiplier: 2
      require {
        damaged_by: TARGET_ALL
      }
    }
  }
}
behavior {
  id: EFFECT_ACROBATICS
  attack {
    power_modifier {
      multiplier: 1.5
      require {
        target: TARGET_MOVE_USER
        item: ITEM_NONE
      }
    }
  }
}
behavior {
  id: EFFECT_HEAT_CRASH
  attack {
    power_modifier {
      flat: 120
      require {
        target: TARGET_MOVE_USER
        relative_weight: 5
      }
    }
    power_modifier {
      flat: 100
      require {
        target: TARGET_MOVE_USER
        relative_weight: 4
      }
    }
    power_modifier {
      flat: 80
      require {
        target: TARGET_MOVE_USER
        relative_weight: 3
      }
    }
    power_modifier {
      flat: 60
      require {
        target: TARGET_MOVE_USER
        relative_weight: 2
      }
    }
    power_modifier {
      flat: 40
    }
  }
}
behavior {
  id: EFFECT_PUNISHMENT
  attack {
    power_modifier {
      formula {
        measurement: MEASUREMENT_TARGET_POSITIVE_STAT_BUFFS
        base: 60
        multiplier: 20
        max: 200
      }
    }
  }
}
behavior {
  id: EFFECT_STORED_POWER
  attack {
    power_modifier {
      formula {
        measurement: MEASUREMENT_ATTACKER_POSITIVE_STAT_BUFFS
        multiplier: 20
      }
    }
  }
}
behavior {
  id: EFFECT_ELECTRO_BALL
  attack {
    power_modifier {
      flat: 150
      require {
        target: TARGET_MOVE_USER
        relative_speed: 4
      }
    }
    power_modifier {
      flat: 120
      require {
        target: TARGET_MOVE_USER
        relative_speed: 3
      }
    }
    power_modifier {
      flat: 80
      require {
        target: TARGET_MOVE_USER
        relative_speed: 2
      }
    }
    power_modifier {
      flat: 60
      require {
        target: TARGET_MOVE_USER
        relative_speed: 1
      }
    }
    power_modifier {
      flat: 40
    }
  }
}
behavior {
  id: EFFECT_GYRO_BALL
  attack {
    power_modifier {
      formula {
        measurement: MEASUREMENT_TARGET_OVER_ATTACKER_SPEED
        base: 1
        multiplier: 25
        max: 150
      }
    }
  }
}
behavior {
  id: EFFECT_PAYBACK
  attack {
    power_modifier {
      multiplier: 2
      require {
        has_taken_turn: true
      }
    }
  }
}
behavior {
  id: EFFECT_ROUND
  attack {
    effect_from_argument: true
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_PARTNER
        used_same_move_behavior: true
      }
    }
  }
}
behavior {
  id: EFFECT_BRINE
  attack {
    power_modifier {
      multiplier: 2
      require {
        not: true
        hp_percent: 50
      }
    }
  }
}
behavior {
  id: EFFECT_VENOSHOCK
  attack {
    power_modifier {
      multiplier: 2
      require {
        status: STATUS_POISON
      }
    }
  }
}
behavior {
  id: EFFECT_RETALIATE
  attack {
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_MOVE_USER
        ally_fainted_recently: true
      }
    }
  }
}
behavior {
  id: EFFECT_BULLDOZE
  attack {
    effect { effect: MOVE_EFFECT_SPD_MINUS_1 }
  }
}
behavior {
  id: EFFECT_FOUL_PLAY
  attack {
    use_target_stat_as_attacking_stat: true
  }
}
behavior {
  id: EFFECT_PSYSHOCK
  attack { }
}
behavior {
  id: EFFECT_ROOST
  status {
    do {
      change_percent_hp: 50
    }
    do {
      status: STATUS_ROOST
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_GRAVITY
  status {
    do {
      status: STATUS_GRAVITY
    }
  }
}
behavior {
  id: EFFECT_MIRACLE_EYE
  status {
    do {
      status: STATUS_MIRACLE_EYE
    }
  }
}
behavior {
  id: EFFECT_TAILWIND
  status {
    do {
      status: STATUS_TAILWIND
    }
  }
}
behavior {
  id: EFFECT_EMBARGO
  status {
    do {
      status: STATUS_EMBARGO
    }
  }
}
behavior {
  id: EFFECT_AQUA_RING
  status {
    do {
      status: STATUS_AQUA_RING
    }
  }
}
behavior {
  id: EFFECT_TRICK_ROOM
  status {
    do {
      status: STATUS_TRICK_ROOM
    }
  }
}
behavior {
  id: EFFECT_WONDER_ROOM
  status {
    do {
      status: STATUS_WONDER_ROOM
    }
  }
}
behavior {
  id: EFFECT_MAGIC_ROOM
  status {
    do {
      status: STATUS_MAGIC_ROOM
    }
  }
}
behavior {
  id: EFFECT_MAGNET_RISE
  status {
    do {
      status: STATUS_MAGNET_RISE
    }
  }
}
behavior {
  id: EFFECT_TOXIC_SPIKES
  status {
    do {
      status: STATUS_TOXIC_SPIKES
    }
  }
}
behavior {
  id: EFFECT_GASTRO_ACID
  status {
    do {
      status: STATUS_GASTRO_ACID
    }
  }
}
behavior {
  id: EFFECT_STEALTH_ROCK
  status {
    do {
      status: STATUS_STEALTH_ROCK
    }
  }
}
behavior {
  id: EFFECT_TELEKINESIS
  status {
    do {
      status: STATUS_TELEKINESIS
    }
  }
}
behavior {
  id: EFFECT_POWER_SWAP
  status {
    do {
      swap_stat_changes: STAT_ATK
    }
    do {
      swap_stat_changes: STAT_SPATK
    }
    do {
      swap_base_stat: STAT_ATK
    }
    do {
      swap_base_stat: STAT_SPATK
    }
  }
}
behavior {
  id: EFFECT_GUARD_SWAP
  status {
    do {
      swap_stat_changes: STAT_DEF
    }
    do {
      swap_stat_changes: STAT_SPDEF
    }
    do {
      swap_base_stat: STAT_DEF
    }
    do {
      swap_base_stat: STAT_SPDEF
    }
  }
}
behavior {
  id: EFFECT_HEART_SWAP
  status {
    do {
      swap_stat_changes: STAT_ATK
    }
    do {
      swap_stat_changes: STAT_DEF
    }
    do {
      swap_stat_changes: STAT_SPEED
    }
    do {
      swap_stat_changes: STAT_SPATK
    }
    do {
      swap_stat_changes: STAT_SPDEF
    }
    do {
      swap_stat_changes: STAT_ACC
    }
    do {
      swap_stat_changes: STAT_EVASION
    }
  }
}
behavior {
  id: EFFECT_POWER_SPLIT
  status {
    do {
      average_stats: STAT_ATK
    }
    do {
      average_stats: STAT_SPATK
    }
  }
}
behavior {
  id: EFFECT_GUARD_SPLIT
  status {
    do {
      average_stats: STAT_DEF
    }
    do {
      average_stats: STAT_SPDEF
    }
  }
}
behavior {
  id: EFFECT_STICKY_WEB
  status {
    do {
      status: STATUS_STICKY_WEB
    }
  }
}
behavior {
  id: EFFECT_METAL_BURST
  attack {
    counter_damage {
      multiplier: 1.5
      type: COUNTERS_BOTH
    }
  }
}
behavior {
  id: EFFECT_LUCKY_CHANT
  status {
    do {
      status: STATUS_STICKY_WEB
    }
  }
}
behavior {
  id: EFFECT_SUCKER_PUNCH
  attack {
    require {
      not: true
      has_taken_turn: true
    }
    require {
      using_attack: true
    }
  }
}
behavior {
  id: EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2
  attack {
    effect { effect: MOVE_EFFECT_SP_DEF_MINUS_2 }
  }
}
behavior {
  id: EFFECT_SIMPLE_BEAM
  status {
    do {
      set_ability: ABILITY_SIMPLE
    }
  }
}
behavior {
  id: EFFECT_ENTRAINMENT
  status {
    do {
      target: TARGET_MOVE_USER
      copy_ability_to: TARGET_MOVE_TARGET
    }
  }
}
behavior {
  id: EFFECT_HEAL_PULSE
  status {
    do {
      change_percent_hp: 50
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_QUASH
  status {
    do {
      status: STATUS_QUASH
    }
  }
}
behavior {
  id: EFFECT_ION_DELUGE
  status {
    do {
      status: STATUS_ION_DELUGE
    }
  }
}
behavior {
  id: EFFECT_FREEZE_DRY
  attack {
    effect { effect: MOVE_EFFECT_FROSTBITE }
    super_effective_vs: TYPE_WATER
  }
}
behavior {
  id: EFFECT_SHEER_COLD
  attack {
    effect { effect: MOVE_EFFECT_FROSTBITE }
    super_effective_vs: TYPE_WATER
    accuracy {
      always_hit: true
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_HAIL
      }
    }
  }
}
behavior {
  id: EFFECT_TOPSY_TURVY
  status {
    do {
      other: OTHER_INVERT_STATS
    }
  }
}
behavior {
  id: EFFECT_MISTY_TERRAIN
  status {
    do {
      set_terrain: TERRAIN_MISTY
    }
  }
}
behavior {
  id: EFFECT_GRASSY_TERRAIN
  status {
    do {
      set_terrain: TERRAIN_GRASSY
    }
  }
}
behavior {
  id: EFFECT_ELECTRIC_TERRAIN
  status {
    do {
      set_terrain: TERRAIN_ELECTRIC
    }
  }
}
behavior {
  id: EFFECT_PSYCHIC_TERRAIN
  status {
    do {
      set_terrain: TERRAIN_PSYCHIC
    }
  }
}
behavior {
  id: EFFECT_ATTACK_ACCURACY_UP
  attack {
    effect {
      effect: MOVE_EFFECT_ACC_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_ATTACK_SPATK_UP
  attack {
    effect {
      effect: MOVE_EFFECT_SP_ATK_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_HURRICANE
  attack {
    effect { effect: MOVE_EFFECT_CONFUSION }
    accuracy {
      always_hit: true
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_RAIN
      }
    }
    accuracy {
      set_to: 50
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_SUN
      }
    }
  }
}
behavior {
  id: EFFECT_ME_FIRST
  custom_behavior: true
}
behavior {
  id: EFFECT_SPEED_UP_HIT
  attack {
    effect { effect: MOVE_EFFECT_SPD_PLUS_1 }
  }
}
behavior {
  id: EFFECT_QUIVER_DANCE
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_COIL
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_ACC
        amount: 1
      }
    }
    do {
      status: STATUS_COIL_UP
    }
  }
}
behavior {
  id: EFFECT_ELECTRIFY
  status {
    protect_effect: true
    do {
      status: STATUS_ELECTRIFY
    }
  }
}
behavior {
  id: EFFECT_SCALD
  attack {
    effect { effect: MOVE_EFFECT_BURN }
  }
}
behavior {
  id: EFFECT_REFLECT_TYPE
  status {
    do {
      other: OTHER_COPY_TYPE
    }
  }
}
behavior {
  id: EFFECT_SOAK
  status {
    do {
      other: OTHER_SET_TYPE_TO_ARGUMENT
    }
  }
}
behavior {
  id: EFFECT_GROWTH
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
        conditional {
          new_amount: 2
          require {
            weather_affected: WEATHER_SUN
          }
        }
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
        conditional {
          new_amount: 2
          require {
            weather_affected: WEATHER_SUN
          }
        }
      }
    }
  }
}
behavior {
  id: EFFECT_CLOSE_COMBAT
  attack {
    effect {
      effect: MOVE_EFFECT_DEF_SPDEF_DOWN
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_LAST_RESORT
  attack {
    require {
      target: TARGET_MOVE_USER
      last_resort: true
    }
  }
}
behavior {
  id: EFFECT_RECOIL_33_STATUS
  attack {
    recoil_fraction: 3
    effect_from_argument: true
  }
}
behavior {
  id: EFFECT_FLINCH_STATUS
  attack {
    effect_from_argument: true
    additional_effect {
      effect: MOVE_EFFECT_FLINCH
    }
  }
}
behavior {
  id: EFFECT_RECOIL_50
  attack {
    recoil_fraction: 2
  }
}
behavior {
  id: EFFECT_SHELL_SMASH
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: -1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_SHIFT_GEAR
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_UP_3
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: 3
      }
    }
  }
}
behavior {
  id: EFFECT_NOBLE_ROAR
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: -1
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_VENOM_DRENCH
  status {
    require {
      status: STATUS_POISON
      terrain_affected: TERRAIN_TOXIC
    }
    do {
      change_stat {
        stat: STAT_ATK
        amount: -1
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: -1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: -1
      }
    }
  }
}
behavior {
  id: EFFECT_TOXIC_THREAD
  status {
    do {
      status: STATUS_POISON
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: -3
      }
    }
    change_target {
      new_type: BOTH
      require {
        target: TARGET_FIELD
        terrain_affected: TERRAIN_TOXIC
      }
    }
  }
}
behavior {
  id: EFFECT_CLEAR_SMOG
  attack {
    after {
      other: OTHER_CLEAR_STAT_CHANGES
    }
  }
}
behavior {
  id: EFFECT_HIT_SWITCH_TARGET
  attack {
    effect_from_argument: true
    after {
      switch {
        random: true
      }
    }
  }
}
behavior {
  id: EFFECT_FINAL_GAMBIT
  attack {
    user_hp_to_damage: true
    after {
      change_percent_hp: -100
      hp_drain_lethal: true
    }
  }
}
behavior {
  id: EFFECT_CHANGE_TYPE_ON_ITEM
  attack {
    type_change {
      item_type: true
      require {
        target: TARGET_MOVE_USER
        hold_effect_matches_argument: true
      }
    }
  }
}
behavior {
  id: EFFECT_AUTOTOMIZE
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 2
      }
    }
    do {
      status: STATUS_AUTOTOMIZE
    }
  }
}
behavior {
  id: EFFECT_COPYCAT
  custom_behavior: true
}
behavior {
  id: EFFECT_DEFOG
  status {
    do {
      change_stat {
        stat: STAT_EVASION
        amount: -1
      }
    }
    do {
      other: OTHER_CLEAR_FIELD
    }
  }
}
behavior {
  id: EFFECT_HIT_ENEMY_HEAL_ALLY
  ally_enemy_differ {
    ally {
      do {
        change_percent_hp: 50
      }
    }
  }
}
behavior {
  id: EFFECT_SMACK_DOWN
  attack {
    effect_from_argument: true
    additional_effect { effect: MOVE_EFFECT_SMACK_DOWN }
  }
}
behavior {
  id: EFFECT_SYNCHRONOISE
  attack {
    type_change {
      first_type: true
    }
  }
}
behavior {
  id: EFFECT_PSYCHO_SHIFT
  custom_behavior: true
}
behavior {
  id: EFFECT_POWER_TRICK
  status {
    do {
      other: OTHER_SWAP_ATK_AND_DEF
    }
    do {
      other: OTHER_SWAP_ATK_AND_DEF_BOOSTS
    }
  }
}
behavior {
  id: EFFECT_FLAME_BURST
  attack {
    effect {
      effect: MOVE_EFFECT_FLAME_BURST
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_AFTER_YOU
  status {
    do {
      status: STATUS_AFTER_YOU
    }
  }
}
behavior {
  id: EFFECT_BESTOW
  status {
    do {
      other: OTHER_GIVE_ITEM
    }
  }
}
behavior {
  id: EFFECT_ROTOTILLER
  status {
    do {
      target: TARGET_ALL
      change_stat {
        stat: STAT_ATK
        amount: 1
        conditional {
          new_amount: 2
          require {
            target: TARGET_LOOP_TARGET
            terrain_affected: TERRAIN_GRASSY
          }
        }
      }
      require {
        target: TARGET_LOOP_TARGET
        battler_type: TYPE_GRASS
      }
    }
    do {
      target: TARGET_ALL
      change_stat {
        stat: STAT_SPATK
        amount: 1
        conditional {
          new_amount: 2
          require {
            target: TARGET_LOOP_TARGET
            terrain_affected: TERRAIN_GRASSY
          }
        }
      }
      require {
        target: TARGET_LOOP_TARGET
        battler_type: TYPE_GRASS
      }
    }
  }
}
behavior {
  id: EFFECT_FLOWER_SHIELD
  status {
    do {
      target: TARGET_ALL
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
      require {
        target: TARGET_LOOP_TARGET
        battler_type: TYPE_GRASS
      }
    }
  }
}
behavior {
  id: EFFECT_HIT_PREVENT_ESCAPE
  attack {
    effect { effect: MOVE_EFFECT_PREVENT_ESCAPE }
  }
}
behavior {
  id: EFFECT_SPEED_SWAP
  status {
    do {
      swap_stat_changes: STAT_SPEED
    }
    do {
      swap_base_stat: STAT_SPEED
    }
  }
}
behavior {
  id: EFFECT_DEFENSE_UP2_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_DEF_PLUS_2
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_REVELATION_DANCE
  attack {
    type_change {
      first_type: true
    }
  }
}
behavior {
  id: EFFECT_AURORA_VEIL
  status {
    require {
      weather_affected: WEATHER_HAIL
    }
    do {
      status: STATUS_AURORA_VEIL
    }
  }
}
behavior {
  id: EFFECT_THIRD_TYPE
  status {
    do {
      other: OTHER_SET_THIRD_TYPE_TO_ARGUMENT
    }
  }
}
behavior {
  id: EFFECT_TRICK_OR_TREAT
  status {
    do {
      other: OTHER_SET_THIRD_TYPE_TO_ARGUMENT
    }
    do {
      status: STATUS_TRICK_OR_TREAT
    }
  }

}
behavior {
  id: EFFECT_FEINT
  attack {
    effect { effect: MOVE_EFFECT_FEINT }
  }
}
behavior {
  id: EFFECT_SPARKLING_ARIA
  ally_enemy_differ {
    ally {
      do {
        other: OTHER_CLEAR_STATUS
        require {
          status: STATUS_BURN
        }
      }
    }
    enemy {
      after {
        other: OTHER_CLEAR_STATUS
        require {
          status: STATUS_BURN
        }
      }
    }
  }
}
behavior {
  id: EFFECT_ACUPRESSURE
  status {
    do {
      other: OTHER_ACCUPRESSURE
    }
  }
}
behavior {
  id: EFFECT_AROMATIC_MIST
  status {
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 2
      }
    }
    do {
      target: TARGET_PARTNER
      change_stat {
        stat: STAT_SPDEF
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_POWDER
  status {
    do {
      status: STATUS_POWDER
    }
  }
}
behavior {
  id: EFFECT_SP_ATTACK_UP_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_SP_ATK_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_BELCH
  attack {
    require {
      target: TARGET_MOVE_USER
      item_pocket: POCKET_BERRIES
      ate_berry: true
    }
    before {
      target: TARGET_MOVE_USER
      other: OTHER_EAT_BERRY
    }
  }
}
behavior {
  id: EFFECT_PARTING_SHOT
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: -1
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: -1
      }
    }
    do {
      switch {
        target: TARGET_MOVE_USER
      }
    }
  }
}
behavior {
  id: EFFECT_SPECTRAL_THIEF
  attack {
    effect { effect: MOVE_EFFECT_SPECTRAL_THIEF }
  }
}
behavior {
  id: EFFECT_V_CREATE
  attack {
    effect {
      effect: MOVE_EFFECT_V_CREATE
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_MAT_BLOCK
  status {
    protect_effect: true
    do {
      other: OTHER_SET_PROTECT
    }
    require {
      target: TARGET_MOVE_USER
      is_first_turn: true
    }
  }
}
behavior {
  id: EFFECT_STOMPING_TANTRUM
  attack {
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_MOVE_USER
        last_move_failed: true
      }
    }
  }
}
behavior {
  id: EFFECT_CORE_ENFORCER
  attack {
    effect {
      effect: MOVE_EFFECT_CORE_ENFORCER
      certain: true
    }
  }
}
behavior {
  id: EFFECT_INSTRUCT
  custom_behavior: true
}
behavior {
  id: EFFECT_THROAT_CHOP
  attack {
    effect {
      effect: MOVE_EFFECT_THROAT_CHOP
      certain: true
    }
  }
}
behavior {
  id: EFFECT_LASER_FOCUS
  status {
    do {
      status: STATUS_LASER_FOCUS
    }
  }
}
behavior {
  id: EFFECT_MAGNETIC_FLUX
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
      require {
        ability: ABILITY_PLUS
        ability: ABILITY_MINUS
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
      require {
        ability: ABILITY_PLUS
        ability: ABILITY_MINUS
      }
    }
    do {
      target: TARGET_PARTNER
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
      require {
        target: TARGET_PARTNER
        ability: ABILITY_PLUS
        ability: ABILITY_MINUS
      }
    }
    do {
      target: TARGET_PARTNER
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
      require {
        target: TARGET_PARTNER
        ability: ABILITY_PLUS
        ability: ABILITY_MINUS
      }
    }
  }
}
behavior {
  id: EFFECT_GEAR_UP
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_INCINERATE
  attack {
    effect {
      effect: MOVE_EFFECT_INCINERATE
      certain: true
    }
  }
}
behavior {
  id: EFFECT_BUG_BITE
  attack {
    effect {
      effect: MOVE_EFFECT_BUG_BITE
      certain: true
    }
  }
}
behavior {
  id: EFFECT_STRENGTH_SAP
  status {
    do {
      drain_stat_and_heal: STAT_ATK
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_MIND_BLOWN
  attack {
    attack_all_in_loop {
      before_loop {
        change_percent_hp: -50
        hp_drain_lethal: true
      }
      attack {
        effect_from_argument: true
      }
    }
  }
}
behavior {
  id: EFFECT_PURIFY
  status {
    do {
      other: OTHER_CLEAR_STATUS
      failure_fails_move: true
    }
    do {
      change_percent_hp: 50
    }
  }
}
behavior {
  id: EFFECT_BURN_UP
  attack {
    require {
      target: TARGET_MOVE_USER
      battler_matches_move_type: true
    }
    effect { effect: MOVE_EFFECT_BURN_UP }
  }
}
behavior {
  id: EFFECT_SHORE_UP
  status {
    do {
      other: OTHER_RESTORE_HP_WEATHER_BASED
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_GEOMANCY
  two_turn {
    turn_2_status {
      do {
        change_stat {
          stat: STAT_SPATK
          amount: 2
        }
      }
      do {
        change_stat {
          stat: STAT_SPDEF
          amount: 2
        }
      }
      do {
        change_stat {
          stat: STAT_SPEED
          amount: 2
        }
      }
    }
  }
}
behavior {
  id: EFFECT_FAIRY_LOCK
  status {
    do {
      status: STATUS_FAIRY_LOCK
    }
  }
}
behavior {
  id: EFFECT_ALLY_SWITCH
  status {
    do {
      other: OTHER_ALLY_SWITCH
    }
  }
}
behavior {
  id: EFFECT_RELIC_SONG
  attack {
    effect_from_argument: true
  }
}
behavior {
  id: EFFECT_ATTACKER_DEFENSE_DOWN_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_DEF_MINUS_1
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_BODY_PRESS
  attack {
    different_attacking_stat: STAT_DEF
  }
}
behavior {
  id: EFFECT_EERIE_SPELL
  attack {
    accuracy {
      always_hit: true
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_FOG
      }
    }
    accuracy {
      set_to: 50
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_SUN
      }
    }
    after {
      reduce_pp {
        min: 6
        max: 6
      }
    }
  }
}
behavior {
  id: EFFECT_DEPLETION_BEAM
  attack {
    after {
      reduce_pp {
        min: 3
        max: 3
      }
    }
  }
}
behavior {
  id: EFFECT_JUNGLE_HEALING
  status {
    do {
      other: OTHER_CLEAR_STATUS
    }
    do {
      target: TARGET_PARTNER
      other: OTHER_CLEAR_STATUS
    }
    do {
      change_percent_hp: 25
    }
    do {
      target: TARGET_PARTNER
      change_percent_hp: 25
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_COACHING
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_LASH_OUT
  attack {
    power_modifier {
      formula {
        measurement: MEASUREMENT_ATTACKER_NEGATIVE_STAT_BUFFS
        multiplier: 20
        use_move_base: true
        max: 140
      }
    }
  }
}
behavior {
  id: EFFECT_GRASSY_GLIDE
  attack {
    priority {
      amount: 1
      require {
        target: TARGET_MOVE_USER
        terrain_affected: TERRAIN_GRASSY
      }
    }
  }
}
behavior {
  id: EFFECT_DECORATE
  ally_enemy_differ {
    ally {
      do {
        change_stat {
          stat: STAT_ATK
          amount: 2
        }
      }
      do {
        change_stat {
          stat: STAT_SPATK
          amount: 2
        }
      }
      do {
        change_stat {
          stat: STAT_CRIT
          amount: 2
        }
      }
    }
  }
}
behavior {
  id: EFFECT_SNIPE_SHOT
  attack { }
  ignores_redirection: true
}
behavior {
  id: EFFECT_RECOIL_HP_25
  attack {
    recoil_fraction: 4
  }
}
behavior {
  id: EFFECT_STUFF_CHEEKS
  status {
    do {
      other: OTHER_EAT_BERRY
      failure_fails_move: true
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_GRAV_APPLE
  attack {
    effect_from_argument: true
    power_modifier {
      multiplier: 1.5
      require {
        status: STATUS_GRAVITY
      }
    }
  }
}
behavior {
  id: EFFECT_EVASION_UP_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_EVS_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_GLITZY_GLOW
  attack {
    after {
      target: TARGET_MOVE_USER
      status: STATUS_LIGHT_SCREEN
    }
  }
}
behavior {
  id: EFFECT_BADDY_BAD
  attack {
    after {
      target: TARGET_MOVE_USER
      status: STATUS_REFLECT
    }
  }
}
behavior {
  id: EFFECT_SAPPY_SEED
  attack {
    after {
      status: STATUS_LEECH_SEED
    }
  }
}
behavior {
  id: EFFECT_FREEZY_FROST
  attack {
    after {
      other: OTHER_CLEAR_STAT_CHANGES
    }
  }
}
behavior {
  id: EFFECT_SPARKLY_SWIRL
  attack {
    after {
      target: TARGET_MOVE_USER
      other: OTHER_CLEAR_PARTY_STATUS
    }
  }
}
behavior {
  id: EFFECT_PLASMA_FISTS
  attack {
    after {
      status: STATUS_PLASMA_FISTS
    }
  }
}
behavior {
  id: EFFECT_HYPERSPACE_FURY
  attack {
    require {
      target: TARGET_MOVE_USER
      species: SPECIES_HOOPA_UNBOUND
    }
    effect { effect: MOVE_EFFECT_FEINT }
    additional_effect {
      effect: MOVE_EFFECT_DEF_MINUS_1
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_TERRAIN_PULSE
  attack {
    type_change {
      terrain: true
    }
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_MOVE_USER
        terrain_affected: TERRAIN_ANY
      }
    }
  }
}
behavior {
  id: EFFECT_JAW_LOCK
  attack {
    effect {
      effect: MOVE_EFFECT_TRAP_BOTH
      certain: true
    }
  }
}
behavior {
  id: EFFECT_NO_RETREAT
  status {
    do {
      change_stat {
        stat: STAT_ALL
        amount: 1
      }
    }
    do {
      target: TARGET_MOVE_USER
      status: STATUS_PREVENT_ESCAPE
    }
  }
}
behavior {
  id: EFFECT_TAR_SHOT
  status {
    do {
      change_stat {
        stat: STAT_SPEED
        amount: -1
      }
    }
    do {
      status: STATUS_TAR_SHOT
    }
  }
}
behavior {
  id: EFFECT_POLTERGEIST
  attack {
    require {
      not: true
      target: TARGET_MOVE_USER
      item: ITEM_NONE
    }
  }
}
behavior {
  id: EFFECT_OCTOLOCK
  attack {
    after {
      status: STATUS_OCTOLOCK
    }
  }
}
behavior {
  id: EFFECT_CLANGOROUS_SOUL
  status {
    do {
      change_percent_hp: 33
      failure_fails_move: true
    }
    do {
      change_stat {
        stat: STAT_ALL
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_BOLT_BEAK
  attack {
    power_modifier {
      multiplier: 2
      require {
        not: true
        has_taken_turn: true
      }
    }
  }
}
behavior {
  id: EFFECT_RISING_VOLTAGE
  attack {
    power_modifier {
      multiplier: 2
      require {
        terrain_affected: TERRAIN_ELECTRIC
      }
    }
  }
}
behavior {
  id: EFFECT_FROSTBITE_HIT
  attack {
    effect { effect: MOVE_EFFECT_FROSTBITE }
  }
}
behavior {
  id: EFFECT_EXPANDING_FORCE
  attack {
    power_modifier {
      flat: 120
      require {
        target: TARGET_MOVE_USER
        terrain_affected: TERRAIN_PSYCHIC
      }
    }
    change_target {
      new_type: BOTH
      require {
        target: TARGET_FIELD
        terrain_affected: TERRAIN_PSYCHIC
      }
    }
  }
}
behavior {
  id: EFFECT_STEEL_BEAM
  attack {
    after {
      target: TARGET_MOVE_USER
      change_percent_hp: -50
      hp_drain_lethal: true
    }
    on_miss {
      target: TARGET_MOVE_USER
      change_percent_hp: -50
      hp_drain_lethal: true
    }
  }
}
behavior {
  id: EFFECT_HOWL
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      target: TARGET_PARTNER
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_ATTRACT_HIT
  attack {
    effect { effect: MOVE_EFFECT_ATTRACT }
  }
}
behavior {
  id: EFFECT_CURSE_HIT
  attack {
    effect { effect: MOVE_EFFECT_CURSE }
  }
}
behavior {
  id: EFFECT_FLINCH_RECOIL_33
  attack {
    effect { effect: MOVE_EFFECT_FLINCH }
    recoil_fraction: 3
  }
}
behavior {
  id: EFFECT_FLINCH_RECOIL_50
  attack {
    effect { effect: MOVE_EFFECT_FLINCH }
    recoil_fraction: 2
  }
}
behavior {
  id: EFFECT_IGNORE_TYPE_IMMUNITY
  attack {
    neutral_vs_immunity: true
  }
}
behavior {
  id: EFFECT_SE_AGAINST_TYPE_HIT
  attack {
    super_effective_vs_argument: true
  }
}
behavior {
  id: EFFECT_DOUBLE_DMG_IF_STATUS1
  attack {
    power_modifier {
      multiplier: 2
      require {
        has_argument_status: true
      }
    }
  }
}
behavior {
  id: EFFECT_STEALTH_ROCK_HIT
  attack {
    after {
      status: STATUS_STEALTH_ROCK
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_LEECH_SEED_HIT
  attack {
    after {
      status: STATUS_LEECH_SEED
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_STICKY_WEB_HIT
  attack {
    after {
      status: STATUS_STICKY_WEB
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_BLEED_HIT
  attack {
    effect { effect: MOVE_EFFECT_BLEED }
  }
}
behavior {
  id: EFFECT_SLEEP_HIT
  attack {
    effect { effect: MOVE_EFFECT_SLEEP }
  }
}
behavior {
  id: EFFECT_BLEED
  status {
    do {
      status: STATUS_BLEED
    }
  }
}
behavior {
  id: EFFECT_FROSTBITE
  status {
    do {
      status: STATUS_FROSTBITE
    }
  }
}
behavior {
  id: EFFECT_INFERNAL_PARADE
  attack {
    power_modifier {
      multiplier: 1.5
      require {
        status: STATUS_STATUS1_ANY
      }
    }
    effect_from_argument: true
  }
}
behavior {
  id: EFFECT_BERRY_SMASH
  attack {
    before {
      target: TARGET_MOVE_USER
      other: OTHER_EAT_BERRY
    }
  }
}
behavior {
  id: EFFECT_INVERSE_ROOM
  status {
    do {
      status: STATUS_INVERSE_ROOM
    }
  }
}
behavior {
  id: EFFECT_DRAIN_BRAIN
  status {
    do {
      drain_stat_and_heal: STAT_SPATK
    }
  }
  healing_effect: true
}
behavior {
  id: EFFECT_TRIPLE_ARROWS
  attack {
    effect {
      effect: MOVE_EFFECT_DEF_MINUS_1
    }
    additional_effect {
      effect: MOVE_EFFECT_FLINCH
      chance: 30
    }
  }
}
behavior {
  id: EFFECT_RECOIL_25_STATUS
  attack {
    effect_from_argument: true
    recoil_fraction: 4
  }
}
behavior {
  id: EFFECT_WEATHER_BOOST
  attack {
    weather_boost: true
  }
}
behavior {
  id: EFFECT_MORTAL_SPIN
  attack {
    effect_from_argument: true
    additional_effect {
      effect: MOVE_EFFECT_RAPIDSPIN
      affects_user: true
      certain: true
    }
  }
}
behavior {
  id: EFFECT_KARMA
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_REMOVE_TERRAIN_NO_FAIL
  attack {
    effect_from_argument: true
    after {
      other: OTHER_CLEAR_TERRAIN
    }
  }
}
behavior {
  id: EFFECT_TEN_HITS
  attack {
    multihit { type: MULTIHIT_TEN }
    multihits_can_miss: true
  }
}
behavior {
  id: EFFECT_TWO_TURN_SECONDARY
  two_turn {
    turn_1 {
      do {
        run_argument_move_effect: true
      }
    }
    turn_2_attack { }
  }
}
behavior {
  id: EFFECT_SPECIAL_ATTACK_UP_HIT
  attack {
    effect {
      effect: MOVE_EFFECT_SP_ATK_PLUS_1
      affects_user: true
    }
  }
}
behavior {
  id: EFFECT_ARGUMENT_HIT
  attack {
    effect_from_argument: true
  }
}
behavior {
  id: EFFECT_DREAM_INVERSION
  attack {
    effect_from_argument: true
    power_modifier {
      multiplier: 2
      require {
        status: STATUS_SLEEP
      }
    }
  }
}
behavior {
  id: EFFECT_EVERY_OTHER_TURN
  attack { }
}
behavior {
  id: EFFECT_RAGE_FIST
  attack {
    power_modifier {
      formula {
        measurement: MEASUREMENT_TOOK_DAMAGE
        multiplier: 20
        use_move_base: true
        max_bonus: 120
      }
    }
  }
}
behavior {
  id: EFFECT_LAST_RESPECTS
  attack {
    power_modifier {
      formula {
        measurement: MEASUREMENT_FAINTED_BATTLERS
        multiplier: 10
        use_move_base: true
      }
    }
  }
}
behavior {
  id: EFFECT_FICKLE_BEAM
  attack {
    power_modifier {
      multiplier: 2
      require {
        random: 30
      }
    }
  }
}
behavior {
  id: EFFECT_TRANSMUTE
  attack {
    on_faint_target {
      target: TARGET_MOVE_USER
      other: OTHER_RESTORE_ITEM
    }
  }
}
behavior {
  id: EFFECT_TERROR_LOCKS
  attack {
    effect_from_argument: true
    power_modifier {
      multiplier: 1.5
      require {
        status: STATUS_BLEED
      }
    }
  }
}
behavior {
  id: EFFECT_OMINOUS_WIND
  attack {
    effect {
      effect: MOVE_EFFECT_ALL_STATS_UP
      affects_user: true
    }
    power_modifier {
      multiplier: 2
      require {
        target: TARGET_MOVE_USER
        weather_affected: WEATHER_FOG
      }
    }
  }
}
behavior {
  id: EFFECT_IVY_CUDGEL
  attack {
    type_change {
      type: TYPE_GRASS
      require {
        target: TARGET_MOVE_USER
        species: SPECIES_OGERPON
      }
    }
    type_change {
      type: TYPE_FIRE
      require {
        target: TARGET_MOVE_USER
        species: SPECIES_OGERPON_HEARTHFLAME_MASK
        species: SPECIES_OGERPON_HEARTHFLAME_MASK_MEGA
      }
    }
    type_change {
      type: TYPE_WATER
      require {
        target: TARGET_MOVE_USER
        species: SPECIES_OGERPON_WELLSPRING_MASK
        species: SPECIES_OGERPON_WELLSPRING_MASK_MEGA
      }
    }
    type_change {
      type: TYPE_ROCK
      require {
        target: TARGET_MOVE_USER
        species: SPECIES_OGERPON_CORNERSTONE_MASK
        species: SPECIES_OGERPON_CORNERSTONE_MASK_MEGA
      }
    }
  }
}
behavior {
  id: EFFECT_FILLET_AWAY
  status {
    do {
      change_current_percent_hp: -50
      failure_fails_move: true
    }
    do {
      print: "{B_ATK_NAME_WITH_PREFIX} cut its own HP and raised its stats!"
    }
    do {
      change_stat {
        stat: STAT_ATK
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_COURT_CHANGE
  status {
    do {
      other: OTHER_SWAP_FIELD_EFFECTS
    }
  }
}
behavior {
  id: EFFECT_CHILLY_RECEPTION
  status {
    do {
      print: "{B_ATK_NAME_WITH_PREFIX} tells a chillingly bad joke!"
    }
    do {
      set_weather: WEATHER_HAIL
    }
    do {
      switch { }
    }
  }
}
behavior {
  id: EFFECT_SHED_TAIL
  status {
    do {
      change_percent_hp: -50
      failure_fails_move: true
    }
    do {
      status: STATUS_SUBSTITUTE
      alt_success_string: "{B_ATK_NAME_WITH_PREFIX} shed its tail to create a decoy!"
      failure_fails_move: true
    }
    do {
      switch {
        copy_substitute: true
      }
    }
  }
}
behavior {
  id: EFFECT_GHASTLY_ECHO
  attack {
    after {
      switch {
        target: TARGET_MOVE_USER
        after {
          target: TARGET_MOVE_USER
          status: STATUS_GHASTLY_ECHO
        }
      }
    }
  }
}
behavior {
  id: EFFECT_REVIVAL_BLESSING
  custom_behavior: true
  healing_effect: true
}
behavior {
  id: EFFECT_TIDY_UP
  status {
    do {
      run_move_effect {
        effect: MOVE_EFFECT_RAPIDSPIN
        affects_user: true
        certain: true
      }
    }
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_ACID
  attack {
    super_effective_vs: TYPE_STEEL
    effect { effect: MOVE_EFFECT_SP_DEF_MINUS_1 }
  }
}
behavior {
  id: EFFECT_SLUDGE
  attack {
    super_effective_vs: TYPE_WATER
    effect { effect: MOVE_EFFECT_POISON }
  }
}
behavior {
  id: EFFECT_POISON_GAS
  attack {
    super_effective_vs: TYPE_FLYING
    effect { effect: MOVE_EFFECT_POISON }
  }
}
behavior {
  id: EFFECT_PARALYZE_IGNORE_TYPE
  status {
    do {
      status: STATUS_PARALYZE_IGNORE_TYPE
    }
  }
}
behavior {
  id: EFFECT_SUPER_FANG_HAZE
  attack {
    percent_hp_damage: 50
    after {
      other: OTHER_CLEAR_STAT_CHANGES
    }
  }
}
behavior {
  id: EFFECT_SPICY_EXTRACT
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 2
      }
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: -2
      }
    }
    do {
      status: STATUS_CONFUSE
    }
  }
}
behavior {
  id: EFFECT_CLEAR_WEATHER_AND_TERRAIN_HIT
  attack {
    after {
      other: OTHER_CLEAR_WEATHER
    }
    after {
      other: OTHER_CLEAR_TERRAIN
    }
  }
}
behavior {
  id: EFFECT_MATCHA_GOTCHA
  attack {
    effect { effect: MOVE_EFFECT_BURN }
    absorb_damage: true
  }
  healing_effect: true
}
behavior {
  id: EFFECT_DOODLE
  status {
    do {
      copy_ability_to: TARGET_MOVE_USER
    }
    do {
      copy_ability_to: TARGET_PARTNER
    }
  }
}
behavior {
  id: EFFECT_SPIKE_HIT
  attack {
    after {
      target: TARGET_MOVE_USER
      status: STATUS_SPIKES
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_VICTORY_DANCE
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_DEF
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_DRAGON_CHEER
  status {
    do {
      change_stat {
        stat: STAT_CRIT
        amount: 1
        conditional {
          new_amount: 2
          require {
            battler_type: TYPE_DRAGON
          }
        }
      }
    }
    do {
      target: TARGET_PARTNER
      change_stat {
        stat: STAT_CRIT
        amount: 1
        conditional {
          new_amount: 2
          require {
            target: TARGET_PARTNER
            battler_type: TYPE_DRAGON
          }
        }
      }
    }
  }
}
behavior {
  id: EFFECT_SHELTER
  status {
    do {
      change_stat {
        stat: STAT_DEF
        amount: 2
      }
    }
    do {
      target: TARGET_PARTNER
      change_stat {
        stat: STAT_DEF
        amount: 2
      }
    }
  }
}
behavior {
  id: EFFECT_ARGUMENT_HIT_IF_STAT_UP
  attack {
    effect_from_argument_if {
      has_stat_up: true
    }
  }
}
behavior {
  id: EFFECT_UPPER_HAND
  attack {
    effect { effect: MOVE_EFFECT_FLINCH }
    require { using_priority_move: true }
  }
}
behavior {
  id: EFFECT_ELECTRO_SHOT
  two_turn {
    turn_1 {
      do {
        change_stat {
          stat: STAT_SPATK
          amount: 1
        }
      }
    }
    turn_2_attack { }
    accelerate_if {
      target: TARGET_MOVE_USER
      weather_affected: WEATHER_RAIN
    }
  }
}
behavior {
  id: EFFECT_SHARPEN
  status {
    do {
      change_stat {
        stat: STAT_HIGHEST_ATTACK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_CRIT
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SCARY_FACE
  status {
    do {
      status: STATUS_FEAR
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: -2
      }
    }
  }
}
behavior {
  id: EFFECT_SMOKESCREEN
  status {
    do {
      status: STATUS_SMOKESCREEN
    }
  }
}
behavior {
  id: EFFECT_EERIE_FOG
  status {
    do {
      set_weather: WEATHER_FOG
    }
    change_target {
      new_type: ALL_BATTLERS
      require {
        target: TARGET_MOVE_USER
        not: true
        ability: ABILITY_FORECAST
      }
    }
  }
}
behavior {
  id: EFFECT_MYSTIC_DANCE
  status {
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPEED
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_SNAP_JAW
  attack {
    random_effect {
      effect {
        effect: MOVE_EFFECT_SPD_MINUS_1
      }
      effect {
        effect: MOVE_EFFECT_SPD_PLUS_1
        affects_user: true
      }
    }
  }
}
behavior {
  id: EFFECT_RIP_AND_TEAR
  attack {
    effect {
      effect: MOVE_EFFECT_SPD_MINUS_1
      chance: 100
    }
    additional_effect {
      effect: MOVE_EFFECT_BLEED
    }
  }
}
behavior {
  id: EFFECT_SKY_DROP
  two_turn {
    turn_1 {
      do {
        status: STATUS_SKY_DROP
      }
    }
    turn_2_attack {
      before {
        remove_status: STATUS_SKY_DROP
      }
      after {
        other: OTHER_TRIGGER_HAZARDS
      }
    }
  }
}
behavior {
  id: EFFECT_SEISMIC_TOSS
  two_turn {
    turn_1 {
      do {
        status: STATUS_SKY_DROP
      }
    }
    turn_2_attack {
      level_damage: true
      before {
        remove_status: STATUS_SKY_DROP
      }
      after {
        other: OTHER_TRIGGER_HAZARDS
      }
    }
  }
}
behavior {
  id: EFFECT_TERROR_CHARGE
  attack {
    effect { effect: MOVE_EFFECT_BLEED }
    additional_effect { effect: MOVE_EFFECT_FEAR }
  }
}
behavior {
  id: EFFECT_TAILWIND_HIT
  attack {
    after {
      status: STATUS_TAILWIND
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_SANDSTORM_HIT
  attack {
    after {
      set_weather: WEATHER_SANDSTORM
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_RAIN_HIT
  attack {
    after {
      set_weather: WEATHER_RAIN
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_FAIRY_TERRAIN_HIT
  attack {
    after {
      set_terrain: TERRAIN_MISTY
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_CREEPING_THORNS_HIT
  attack {
    after {
      status: STATUS_STEALTH_ROCK
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_TAKE_HEART
  status {
    do {
      other: OTHER_CLEAR_STATUS
    }
    do {
      change_stat {
        stat: STAT_SPATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_CLEAR_SKIES
  status {
    do {
      status: STATUS_CLEAR_SKIES
    }
  }
}
behavior {
  id: EFFECT_SHOWTIME
  status {
    do {
      other: OTHER_SHOWTIME
    }
    do {
      switch { }
    }
  }
}
behavior {
  id: EFFECT_TREPIDATION
  attack {
    after {
      status: STATUS_TREPIDATION
    }
  }
}
behavior {
  id: EFFECT_CHIP_AWAY
  attack {
    effect { effect: MOVE_EFFECT_ATK_MINUS_1 }
    additional_effect { effect: MOVE_EFFECT_DEF_MINUS_1 }
  }
}
behavior {
  id: EFFECT_MEDITATE
  status {
    do {
      change_stat {
        stat: STAT_ATK
        amount: 1
      }
    }
    do {
      change_stat {
        stat: STAT_SPDEF
        amount: 1
      }
    }
  }
}
behavior {
  id: EFFECT_BARRIER
  status {
    require {
      target: TARGET_FIELD
      terrain_affected: TERRAIN_PSYCHIC
    }
    do {
      status: STATUS_REFLECT
    }
    do {
      status: STATUS_LIGHT_SCREEN
    }
  }
}
behavior {
  id: EFFECT_KINESIS
  status {
    do {
      other: OTHER_LOSE_ITEM
    }
    do {
      run_move_effect { effect: MOVE_EFFECT_FLINCH }
    }
  }
}
behavior {
  id: EFFECT_CORROSIVE_GAS
  attack {
    effect { effect: MOVE_EFFECT_KNOCK_OFF }
  }
}
behavior {
  id: EFFECT_CALTROPS
  status {
    do {
      status: STATUS_CALTROPS
    }
  }
}
behavior {
  id: EFFECT_SWEET_KISS
  status {
    do {
      status: STATUS_CONFUSE
    }
    do {
      status: STATUS_ATTRACT
    }
  }
}
behavior {
  id: EFFECT_QUICK_GUARD
  status {
    do {
      status: STATUS_QUICK_GUARD
    }
  }
}
behavior {
  id: EFFECT_TWO_TURN_RETALIATION
  two_turn {
    turn_1 {
      do {
        target: TARGET_MOVE_USER
        status: STATUS_BEAK_BLAST
      }
    }
    turn_2_attack {
      effect_from_argument: true
    }
  }
}
behavior {
  id: EFFECT_SHELL_TRAP
  attack {
    target_last_hit_by: COUNTERS_PHYSICAL
  }
}
behavior {
  id: EFFECT_GRASSY_TERRAIN_HIT
  attack {
    after {
      set_terrain: TERRAIN_GRASSY
      use_effect_chance: true
    }
  }
}
behavior {
  id: EFFECT_TOXIC_TERRAIN
  status {
    do {
      set_terrain: TERRAIN_TOXIC
    }
  }
}
